{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-pg.serviceAccountName" . }}
  labels:
{{ include "simple-pg.labels" . | nindent 4 }}
{{- end -}}
